version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
    timezone: Europe/Amsterdam
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.13
    - 7.13.14
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.12
    - 7.13.8
    - 7.13.9
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
  - dependency-name: sinon-chai
    versions:
    - 3.6.0
  - dependency-name: karma
    versions:
    - 6.0.1
    - 6.0.3
    - 6.1.0
    - 6.1.1
    - 6.3.1
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.3
    - 4.3.4
  - dependency-name: mocha
    versions:
    - 8.3.0
    - 8.3.1
  - dependency-name: eslint-plugin-promise
    versions:
    - 4.3.1
  - dependency-name: sinon
    versions:
    - 9.2.4
  - dependency-name: socket.io
    versions:
    - 2.4.1
